export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const USER_LOGOUT = "USER_LOGOUT"
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
